### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [alireza-hosseini/ipcamera_driver#5]
Would you mind releasing this package also for noetic?

If you can grant me access to the https://github.com/alireza-hosseini/ipcamera_driver-release repository I'm willing to do it as well!

**Comment by alireza-hosseini** [comment]
Hi Timple,

Can you please create a pull request in the release repository containing the required changes for the new ROS version?

**Comment by Timple** [comment]
No, that won't work. The bloom tooling makes lots of changes on lots of branches. This cannot simply be PR-ed.

If you're hesistant about granting me access, I can also make a new release repository for just noetic.

Or you could simply give it a shot, the command is as follows:

```
bloom-release ipcamera_driver --rosdistro noetic
```

**Comment by alireza-hosseini** [comment]
@Timple I just added you as a collaborator to that repository. You need to accept the invitation. If you still didn't have enough rights, please let me know. Thanks for your collaboration.

**Comment by Timple** [comment]
Done! Tracking here: https://github.com/ros/rosdistro/pull/31768

**Comment by Timple** [comment]
Merged. Thank you for creating this package in the first place. And being responsive to follow-ups 👍
